### ISSUE TITLE
Data Sending Time

### ISSUE THREAD

**Issue by Techo2Pranay** [JiriBilek/WiFiSpiESP#21]
Im sending 32 Kbytes each time from master to esp8266 to cloud, it takes total time 10sec. How we can reduce this time to min 5 Sec.

**Comment by JAndrassy** [comment]
I guess it is a problem in your sketch

**Comment by JiriBilek** [comment]
Hi, can you try to send e.g. 8 KB and see if the time is four times less (i.e. 2.5 s)?
Next, as jandrassy wrote, check timings in your sketch.
And last, without MCVE (https://stackoverflow.com/help/minimal-reproducible-example) it is difficult to help.

**Comment by JiriBilek** [comment]
I don't know if you are still interested in the issue, however, the long transmit times might be caused by sending short messages, i.e. sending one byte after another. The SPI protokol used by the ESP8266 hardware is **the most effective for larger messages** (I think 32 bytes at one will be ok). In fact, sending 1 byte and sending 30 bytes takes the same time. And there is nothing we can do about it, unfortunately.

**Comment by JiriBilek** [comment]
Stale issue
